spring:
  application:
    name: banking-api

  datasource:
    url: jdbc:mysql://localhost:3306/banking_api
    username: root
    password: ${Senha_BancoApi}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
        format_sql: true
    deferred-datasource-initialization: true


  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

  packages-to-scan: com.banking.api.controller